name: project_x_movie_mobile
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  provider: ^6.0.5

  #locator
  get_it: ^7.6.0

  shimmer: ^3.0.0

  gap: ^3.0.0

  #Mobx part
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3

  #Network
  json_serializable: ^6.6.1
  json_annotation: ^4.8.1
  dio: ^5.3.3
  either_dart: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Encode
      fonts:
        - asset: asset/font/encode/encode-black.ttf
          weight: 900
        - asset: asset/font/encode/encode-extra-bold.ttf
          weight: 800
        - asset: asset/font/encode/encode-bold.ttf
          weight: 700
        - asset: asset/font/encode/encode-semi-bold.ttf
          weight: 600
        - asset: asset/font/encode/encode-medium.ttf
          weight: 500
        - asset: asset/font/encode/encode-regular.ttf
          weight: 400
        - asset: asset/font/encode/encode-light.ttf
          weight: 300
        - asset: asset/font/encode/encode-thin.ttf
          weight: 200
        - asset: asset/font/encode/encode-extra-light.ttf
          weight: 100
