name: search
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core
  genre:
    path: ../genre
  project_x_movie_mobile:
    path: ../../

  dio: ^5.3.3
  json_serializable: ^6.6.1
  json_annotation: ^4.8.1
  gap: ^3.0.0
  #Mobx part
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
